In [2]:
import pandas as pd
import requests

In [4]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [5]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,49.7673,8.717,30005
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,37.4539,8.687,22668
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,25.9014,8.573,13726
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7128,8.567,17249
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,20.1853,8.556,9848

In [13]:
df = pd.DataFrame()

In [14]:
df

Empty DataFrame
Columns: []
Index: []

In [18]:
temp_df.shape

(20, 7)

In [26]:
df.to_csv("movies.csv")

In [27]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,49.7673,8.717,30005
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,37.4539,8.687,22668
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,25.9014,8.573,13726
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7128,8.567,17249
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,20.1853,8.556,9848

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            40 non-null     int64
 1   title         40 non-null     str
 2   overview      40 non-null     str
 3   release_date  40 non-null     str
 4   popularity    40 non-null     float64
 5   vote_average  40 non-null     float64
 6   vote_count    40 non-null     int64
dtypes: float64(2), int64(2), str(3)
memory usage: 14.9 KB

In [29]:
df = pd.read_csv("movies.csv")