In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import pandas as pd

df = pd.read_csv('train.csv')
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df = pd.read_csv('train.csv', usecols=['Survived','Age','Fare'])
print(df.head())

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [9]:
df = pd.read_csv('train.csv', usecols=['Survived','Age','Fare'])
print(df.head())

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [10]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [12]:
import pandas as pd

# Titanic dataset load
df = pd.read_csv('train.csv')

# Add new columns with default values
df['SalePrice'] = 0              # numeric column
df['GarageQual'] = 'NA'          # categorical column
df['FireplaceQu'] = 'NA'         # categorical column

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked  SalePrice GarageQual  \
0      0         A/5 21171   7.2500   NaN        S          0         NA
1      0          PC 17599  71.2833   C85        C          0         NA
2      0  STON/O2. 3101282   7.9250   NaN        S          0         NA
3      0            113803  53.1000  C123        S          0         NA
4      0            373450   8.0500   NaN        S          0         NA

  FireplaceQu
0          NA
1          NA
2          NA
3          NA
4          NA

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SalePrice,GarageQual,FireplaceQu
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,NA,NA
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,NA,NA
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,NA,NA
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,NA,NA
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,NA,NA

ValueError: Usecols do not match columns, columns expected but not found: ['SalePrice', 'GarageQual', 'FireplaceQu']